site_name: Auto-LLM Documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

nav:
  - Home: index.md
  - Fundamentals:
      - Overview: fundamentals/start.md
      - Datasets: fundamentals/datasets.md
      - Tasks: fundamentals/nlp_tasks.md
      - Training: fundamentals/training_a_llm.md
      - Evaluating: fundamentals/evaluating_a_llm.md
  - Platform:
      - Step-by-Step: platform/how_to_use.md
