model: hf-mistral3
model_args:
  pretrained: mistralai/Ministral-3-8B-Instruct-2512-BF16
  dtype: bfloat16

include_path: tasks
tasks:
  - cofun_ner
  - archaeo_ner
  - wiki_biography_ner
  - fairagro_de_ner

num_fewshot: 5
batch_size: 16
device: cuda:0

apply_chat_template: true
fewshot_as_multiturn: true

output_path: eval_results
log_samples: true

wandb_args:
  project: german-ner-eval
  entity: llm4kmu
  name: pre_few_shot_all_ner_ministral-3-8B-instruct
  tags:
    - ministral-3-8B-instruct
    - few_shot
    - cofun_ner
    - archaeo_ner
    - wiki_biography_ner
    - fairagro_de_ner
