task: pubmed_gen_qa

dataset_path: llm-4-kmu/pubmed_gen_qa
test_split: test

doc_to_text: |
  Answer the following question based on the given context.

  {{input_text}}

  Answer:
doc_to_target: "{{output_text}}"

process_results: !function utils.process_results

metric_list:
  - metric: bleu
    aggregation: mean
    higher_is_better: true
  - metric: rouge1
    aggregation: mean
    higher_is_better: true
  - metric: rouge2
    aggregation: mean
    higher_is_better: true
  - metric: rougeL
    aggregation: mean
    higher_is_better: true

metadata:
  version: 1.0