auto_llm_trainer_args:
  trainer_type: sft
  model_name: meta-llama/Meta-Llama-3-8B
  attn_implementation: sdpa
  truncation: True
  completion_only_loss: True


quantization_config:
  load_in_4bit: True
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: True
  bnb_4bit_compute_dtype: "float16"

peft_config:
  r: 8
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules: "all-linear"
  task_type: "CAUSAL_LM"

trainer_data_builder_config:
  dataset_dir: /vol/auto_llm/processed_datasets/qa/pubmedqa
  instruction_template: "Answer the following question based on the given abstract. Answer only with a yes/no/maybe."
  input_template: "{{input}}\nAnswer:"
  output_template: "{{output}}"
  dataset_type: prompt_completions
  instruction_input_separator: "\n"
  parse_output_as_json: False

trainer_args:
  optim: "paged_adamw_8bit"
  max_length: 1024
  bf16: False
  fp16: True

  # bsz related
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 32  # 4 processes
  auto_find_batch_size: False

  # training related
  output_dir: /vol/auto_llm/sft_models/qa_pubmed_mcqa_llama-3-8b_qlora
  gradient_checkpointing: True
  num_train_epochs: 5
  learning_rate: 1e-4
  warmup_steps: 100

  # tracking/logging related
  report_to: wandb
  run_name: qa_pubmed_mcqa_llama-3-8b_qlora
  logging_steps: 500

  # eval/save related
  eval_strategy: steps
  save_strategy: epoch
