auto_llm_trainer_args:
  trainer_type: sft
  model_name: google/gemma-2-2b
  attn_implementation: eager # keep eager for gemma 
  truncation: True
  completion_only_loss: True

quantization_config:
  load_in_4bit: True
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: True
  bnb_4bit_compute_dtype: "bfloat16"

peft_config:
  r: 32
  lora_alpha: 64
  lora_dropout: 0.05
  target_modules: "all-linear"
  task_type: "CAUSAL_LM"

trainer_data_builder_config:
  dataset_dir: /vol/auto_llm/processed_datasets/qa/pubmedqa
  instruction_template: "<start_of_turn>user\nAnswer the following question based on the given abstract. Answer only with a yes/no/maybe."
  input_template: "{{input}}<end_of_turn>\n<start_of_turn>model\nAnswer:"
  output_template: "{{output}}<end_of_turn>"
  instruction_input_separator: "" 
  dataset_type: prompt_completions
  parse_output_as_json: False

trainer_args:
  optim: "paged_adamw_8bit"
  max_length: 1024
  bf16: True
  fp16: False

  # bsz related
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 8  # 4 processes
  auto_find_batch_size: True

  # training related
  output_dir: /vol/auto_llm/sft_models/qa_pubmed_mcqa_gemma-2-2b_qlora
  gradient_checkpointing: True
  num_train_epochs: 5
  learning_rate: 2e-5
  warmup_steps: 0.05
  lr_scheduler_type: "cosine" 

  # tracking/logging related
  report_to: wandb
  run_name: qa_pubmed_mcqa_gemma-2-2b_qlora
  logging_steps: 0.1

  # eval/save related
  eval_strategy: steps
  save_strategy: epoch
