model: hf-mistral3
model_args:
  pretrained: mistralai/Ministral-3-8B-Instruct-2512-BF16
  dtype: bfloat16
  peft: /vol/auto_llm/sft_models/lora_ger_ps_ner_ministral-3-8B-instruct_conv_zero-shot

apply_chat_template: True

include_path: tasks
tasks:
  - ger_ps_ner

num_fewshot: 0
batch_size: 16
device: cuda:0

output_path: eval_results
log_samples: true

wandb_args:
  project: german-ner-eval
  name: lora_zero_shot_ger_ps_ner_ministral-3-8B-instruct
  tags:
    - legal
    - ger_ps_ner
    - zero_shot