model: hf
model_args:
  pretrained: google/gemma-2-2b
  dtype: bfloat16

include_path: tasks
tasks:
  - german_ler_ner

limit: 10

num_fewshot: 5
batch_size: 16
device: cuda:0

output_path: eval_results
log_samples: true

wandb_args:
  project: german-ner-eval
  name: pre_german_ler_ner_gemma-2-2b
  tags:
    - test
    - legal
    - german_ler_ner
    - few_shot
